
FROM --platform=linux/amd64 ubuntu:20.04

# install system dependencies
RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get -y install python3-pip python3-psycopg2 libpq-dev gunicorn postgresql-client-12 wget npm

RUN npm install @openzeppelin/contracts

RUN wget https://github.com/ethereum/solidity/releases/download/v0.8.16/solc-static-linux && chmod +x ./solc-static-linux && cp solc-static-linux /usr/bin/solc


# install backend dependencies
COPY ./requirements.txt /app/backend/requirements.txt
RUN cd /app/backend && python3 -m pip install -r requirements.txt

# builds the backend
COPY . /app/backend

# disable stdout buffering to avoid losing log messages
ENV PYTHONUNBUFFERED 1

# service is exposed on port 5000, load balancer will take care of the rest
EXPOSE 5000

# switch to a non-root user and start in the backend directory
RUN useradd -ms /bin/bash motyf
USER motyf
WORKDIR /app/backend

CMD [ "gunicorn", "server:app", "--bind", "0.0.0.0:5000", "--timeout", "1000", "--access-logfile", "-" ]
